version: "3"
services:
  node:
    build: .
    env_file:
      - .env
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "8080"
    ports:
      - "80:8080"